import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from 'styled-components'
import { themeDark, themeLight } from './theme/hooks/themeColor'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 

{
  const isDarkModeEnabled = true;

  return (
    <html lang="en">
      <ThemeProvider theme={isDarkModeEnabled ? themeDark : themeLight}>
        <body className={inter.className}>
          {children}
        </body>        
      </ThemeProvider>

    </html>
  )
}
